#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

#define PP_IMPLEMENTATION
#include "pretty-poly.h"

#include "helpers.h"

const int WIDTH = 1024;
const int HEIGHT = 1024;
colour buffer[1024][1024];

colour pen;
void set_pen(colour c) {
  pen = c;
}

void blend_tile(const pp_tile_t *t) {
  for(int32_t y = t->y; y < t->y + t->h; y++) {
    for(int32_t x = t->x; x < t->x + t->w; x++) {     
      colour alpha_pen = pen;
      alpha_pen.rgba.a = alpha(pen.rgba.a, pp_tile_get(t, x, y));
      buffer[y][x] = blend(buffer[y][x], alpha_pen);
    }
  }
}

int main() {
 
  pp_tile_callback(blend_tile);
  pp_antialias(PP_AA_X4);
  pp_clip(0, 0, WIDTH, HEIGHT);

  // ampersand character generated by Alright Fonts made out of three paths 
  // (one outline and two holes)  
  pp_point_t outline[] = {{16, 61}, {14, 59}, {12, 56}, {11, 53}, {10, 50}, {9, 45}, {9, 41}, {12, 36}, {16, 32}, {20, 28}, {31, 24}, {35, 25}, {39, 28}, {43, 31}, {46, 35}, {50, 42}, {48, 49}, {40, 59}, {36, 62}, {47, 75}, {48, 71}, {50, 63}, {64, 63}, {63, 73}, {57, 87}, {69, 100}, {50, 100}, {46, 96}, {43, 98}, {40, 99}, {37, 100}, {33, 100}, {27, 101}, {21, 100}, {15, 98}, {10, 94}, {6, 90}, {3, 80}, {3, 78}, {4, 74}, {6, 71}, {9, 68}, {16, 61}};
  pp_point_t hole1[]   = {{24, 44}, {24, 47}, {28, 53}, {32, 51}, {33, 49}, {34, 48}, {35, 47}, {36, 44}, {35, 43}, {35, 42}, {34, 40}, {32, 39}, {30, 38}, {28, 39}, {27, 39}, {26, 40}, {25, 42}};
  pp_point_t hole2[]   = {{28, 88}, {31, 88}, {37, 86}, {24, 70}, {23, 71}, {21, 74}, {20, 79}, {20, 82}, {21, 84}, {22, 85}, {24, 87}};

  pp_path_t paths[] = {
    {.points = outline, .count = 43},
    {.points = hole1,   .count = 17},
    {.points = hole2,   .count = 11}
  };

  pp_poly_t ampersand = {.paths = paths, .count = 3};

  // draw it!
  set_pen(create_colour(234, 178, 163, 255));
  pp_render(&ampersand);

  stbi_write_png("/tmp/out.png", WIDTH, HEIGHT, 4, (void *)buffer, WIDTH * sizeof(uint32_t));
  
  return 0;
}